<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class SanPhamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('san_phams')->delete();

        DB::table('san_phams')->truncate();

        DB::table('san_phams')->insert([
            //partner 1
            [
                'ten_san_pham'      => 'Nồi cơm điện tử Kangaroo 1.8 lít KG18DR7',
                'slug_san_pham'     => Str::slug('Nồi cơm điện tử Kangaroo 1.8 lít KG18DR7'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '1',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2023/4/12/638168864041148961_noi-com-dien-tu-kangaroo-1-8-lit-kg18dr7-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => '-Kiểu nồi: Nồi cơm điện
                -Dung tích sử dụng: 150 lít - 2 - 3 người',
                'mo_ta_chi_tiet'    => 'Nồi cơm điện tử Kangaroo KG18DR7 có thiết kế nhỏ gọn mà cao cấp, được trang bị công nghệ nấu 1D thông minh cùng với 9 chế độ nấu đa năng, sẽ là lựa chọn hoàn hảo để những người nội trợ nấu ăn được dễ dàng hơn. ',
                'gia_ban'           => 59,
                'gia_khuyen_mai'    => 49,
                'id_chuyen_muc'     => 1,
            ],
            [
                'ten_san_pham'      => 'Nồi cơm điện Sunhouse 1.8 lít SHD8602 ',
                'slug_san_pham'     => Str::slug('Nồi cơm điện Sunhouse 1.8 lít SHD8602 '),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '1',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2021/6/18/637596347192439085_noi-com-dien-sunhouse-1-8-lit-shd8602-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại nồi: Nồi cơm điện
                ',
                'mo_ta_chi_tiet'    => 'Được nghiên cứu và sản xuất dưới sự giám sát chất lượng nghiêm ngặt bởi các chuyên gia Hàn Quốc, nồi cơm điện Sunhouse 1.8 lít SHD8602 sẽ giúp gia đình bạn có được những bữa cơm dẻo ngon chỉ trong thời gian ngắn. Công nghệ hiện đại giúp thiết bị bảo toàn dinh dưỡng trong gạo và rút ngắn thời gian chờ đợi cho người dùng.',
                'gia_ban'           => 28,
                'gia_khuyen_mai'    => 28,
                'id_chuyen_muc'     => 1,
            ],
            [
                'ten_san_pham'      => 'Nồi cơm điện tử Toshiba 1.8 lít RC-18DR3PV(G)',
                'slug_san_pham'     => Str::slug('Nồi cơm điện tử Toshiba 1.8 lít RC-18DR3PV(G)'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '1',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/585x390/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2023/4/10/638167398573251522_noi-com-dien-toshiba-rc-1818dr3pv-g-2.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại nồi: Nồi cơm điện',
                'mo_ta_chi_tiet'    => 'Nồi cơm điện tử Toshiba RC-18DR3PV sở hữu kiểu dáng sang trọng, dung tích lớn, ứng dụng công nghệ nấu 3D mang đến món cơm chín tơi xốp, dẻo ngon mà không bị nhão. Bảng điều khiển nút nhấn với 11 chế độ tự động cho người dùng thoải mái hẹn giờ, để bạn nấu cơm nhàn tênh. .',
                'gia_ban'           => 95,
                'gia_khuyen_mai'    => 79,
                'id_chuyen_muc'     => 1,
            ],
            [
                'ten_san_pham'      => 'Nồi cơm điện Sunhouse 1 lít SHD8208C',
                'slug_san_pham'     => Str::slug('Nồi cơm điện Sunhouse 1 lít SHD8208C'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '1',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2021/5/28/637578201408193143_sunhouse-1-lit-shd8208c-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại nồi: Nồi cơm điện',
                'mo_ta_chi_tiet'    => '- Nồi cơm điện Sunhouse 1 lít SHD8208C với kích thước nhỏ gọn, kiểu dáng hiện đại, trẻ trung và bắt mắt, công suất 400W kết hợp với công nghệ ủ ấm 1D, chính là sản phẩm vô cùng phù hợp cho bữa cơm của những người sống một mình hoặc những gia đình ít người. ',
                'gia_ban'           => 39,
                'gia_khuyen_mai'    => 30,
                'id_chuyen_muc'     => 1,
            ],
            [
                'ten_san_pham'      => 'Nồi cơm nắp gài Kangaroo 1.2 lít KG822',
                'slug_san_pham'     => Str::slug('Nồi cơm nắp gài Kangaroo 1.2 lít KG822'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '1',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2021/6/17/637595480215293669_kangaroo-1-2-lit-kg822-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại nồi :Nồi cơm điện',
                'mo_ta_chi_tiet'    => 'Kangaroo KG822 là chiếc nồi cơm điện nắp gài phù hợp cho gia đình từ hai đến bốn người sử dụng. Sản phẩm được thiết kế nhỏ nhắn tiết kiệm không gian bếp nhưng vẫn nổi bật nhờ màu sắc bắt mắt thu hút sự chú ý. Với hai chế độ nấu và ủ nóng tiên tiến, KG822 sẽ sắm vai trợ thủ đắc lực cho mỗi bữa cơm của gia đình bạn.',
                'gia_ban'           => 65,
                'gia_khuyen_mai'    => 60,
                'id_chuyen_muc'     => 1,
            ],
            [
                'ten_san_pham'      => 'Nồi cơm điện Goldsun 1.8L GRC5001',
                'slug_san_pham'     => Str::slug('Nồi cơm điện Goldsun 1.8L GRC5001'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '1',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2023/4/28/638182707007737324_noi-com-dien-goldsun-18l-grc5001-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại nồi:Nồi cơm điện',
                'mo_ta_chi_tiet'    => '- Nồi cơm điện Goldsun GRC5001 có ngoại hình màu hồng bắt mắt, cùng với đó là nhiều ưu điểm về mặt tính năng để giúp bạn nấu cơm, nấu canh lẫn hấp xôi một cách nhanh chóng nhất mà lại tiết kiệm thời gian. ',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 19,
                'id_chuyen_muc'     => 1,
            ],
            [
                'ten_san_pham'      => 'Nồi cơm điện Kangaroo 1.8 lít KG18RC9',
                'slug_san_pham'     => Str::slug('Nồi cơm điện Kangaroo 1.8 lít KG18RC9'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '1',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2021/12/2/637740645048349025_noi-com-dien-kangaroo-18-lit-kg18rc9-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại nồi:Nồi cơm điện',
                'mo_ta_chi_tiet'    => '- Nồi cơm điện Kangaroo KG18RC9 là sản phẩm thuộc phân khúc tầm trung, chỉ có duy nhất 2 chế độ nấu nhưng đi kèm với đó là công nghệ nấu 3D cùng với nhiều cải tiến về mặt thiết kế giúp nấu và ủ ấm cơm hiệu quả hơn.',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 1,
            ],
            [
                'ten_san_pham'      => 'Nồi cơm điện Sunhouse 1.8 lít SHD8606',
                'slug_san_pham'     => Str::slug('Nồi cơm điện Sunhouse 1.8 lít SHD8606'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '1',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/3/28/637840863878514837_noi-com-dien-sunhouse-1-8-lit-shd8606-bac-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại máy: Nồi cơm điện',
                'mo_ta_chi_tiet'    => 'Khác với những chiếc nồi cơm điện truyền thống có kiểu dáng thấp, nồi cơm điện Sunhouse 1.8 lít SHD8606 có thiết kế kiểu bầu bĩnh độc đáo và trẻ trung khi sử dụng tông màu màu trắng bạc sáng loáng, phù hợp với đa dạng không gian bếp. Thân nồi được làm bằng nhựa cao cấp siêu bền, chịu lực tốt, chịu nhiệt ở mức tối đa để giúp bạn không bị bỏng tay nếu lỡ chạm vào nồi khi đang nấu. ',
                'gia_ban'           => 15,
                'gia_khuyen_mai'    => 10,
                'id_chuyen_muc'     => 1,
            ],


            //partner 2
            [
                'ten_san_pham'      => 'Nồi chiên không dầu Unie 12 lít UE-1000 ',
                'slug_san_pham'     => Str::slug('Nồi chiên không dầu Unie 12 lít UE-1000 '),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '1',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2023/3/27/638155277105812870_noi-chien-khong-dau-unie-10-lit-ue-1000-bac-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại máy: Nồi chiên không dầu',
                'mo_ta_chi_tiet'    => '- Nồi chiên không dầu Unie UE 1000 có dung tích cực lớn, làm chín thức ăn với tốc độ cao bằng công nghệ đối lưu kép, hơn thế nữa còn đi kèm với hơn 10 chức năng nấu khác nhau, sẵn sàng phục vụ cho mọi bữa ăn của gia đình bạn.',
                'gia_ban'           => 69,
                'gia_khuyen_mai'    => 48,
                'id_chuyen_muc'     => 2,
            ],
            [
                'ten_san_pham'      => 'Nồi chiên không dầu Kangaroo 12.5 lít KG12AF6A',
                'slug_san_pham'     => Str::slug('Nồi chiên không dầu Kangaroo 12.5 lít KG12AF6A'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '1',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2023/4/11/638168223711148607_noi-chien-khong-dau-kangaroo-125-lit-kg12af6a-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại nồi: Nồi chiên không dầu',
                'mo_ta_chi_tiet'    => 'Nồi chiên không dầu Kangaroo 12.5 lít KG12AF6A sở hữu kiểu dáng sang trọng, sử dụng công nghệ làm nóng Rapid Air đang được ưa chuộng và được lập trình chi tiết để có thể thay thế đến 9 thiết bị nhà bếp khác nhau, giúp người nội trợ thỏa sức sáng tạo trong gian bếp chỉ cần duy nhất một thiết bị.',
                'gia_ban'           => 29,
                'gia_khuyen_mai'    => 20,
                'id_chuyen_muc'     => 2,
            ],
            [
                'ten_san_pham'      => 'Nồi chiên không dầu Kalite 10 lít Q10)',
                'slug_san_pham'     => Str::slug('Nồi chiên không dầu Kalite 10 lít Q10)'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '1',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/9/26/637997970144675612_noi-chien-khong-dau-kalite-10-lit-q10-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại máy: Nồi chiên không dầu',
                'mo_ta_chi_tiet'    => 'Nồi chiên không dầu Kalite Q10 có thiết kế kiểu lò nướng mini sang trọng và hiện đại, được tích hợp đến 10 chức năng chuyên sâu cho phép nó có thể thay thế hầu hết các thiết bị khác trong nhà bếp, là một trong những sản phẩm nồi chiên không dầu đa chức năng được ưa chuộng nhất hiện nay.',
                'gia_ban'           => 90,
                'gia_khuyen_mai'    => 90,
                'id_chuyen_muc'     => 2,
            ],
            [
                'ten_san_pham'      => 'Nồi chiên không dầu điện tử Kangaroo 8 lít KG8AF1A',
                'slug_san_pham'     => Str::slug('Nồi chiên không dầu điện tử Kangaroo 8 lít KG8AF1A'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '1',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2023/4/12/638168919734213094_noi-chien-khong-dau-dien-tu-kangaroo-8-lit-kg8af1a-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại nồi: Nồi chiên không dầu',
                'mo_ta_chi_tiet'    => '- Nồi chiên không dầu điện tử Kangaroo 8 lít KG8AF1A gây ấn tượng bởi thiết kế hiện đại, trang nhã cùng 10 chế độ nấu đa dạng, có thể thay thế 9 loại thiết bị nhà bếp chuyên dụng. Ngoài ra, sản phẩm còn tích hợp công nghệ Rapid Air làm cho thức ăn chín đều, thơm ngon, tốt cho sức khỏe người sử dụng. ',
                'gia_ban'           => 30,
                'gia_khuyen_mai'    => 30,
                'id_chuyen_muc'     => 2,
            ],
            [
                'ten_san_pham'      => 'Nồi chiên không dầu Hafele HS-AF1102B (535.43.715)',
                'slug_san_pham'     => Str::slug('Nồi chiên không dầu Hafele HS-AF1102B (535.43.715)'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '2',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/10/18/638017036653739972_noi-chien-khong-dau-hafele-hs-af1102b-53543715-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại nồi: Nồi chiên không dầu',
                'mo_ta_chi_tiet'    => 'Là một sản phẩm thuộc thương hiệu Hafele uy tín đến từ Đức, Nồi chiên không dầu Hafele 11 lít HS-AF1102B có thiết kế bắt mắt, công suất lớn đi kèm với nhiều tính năng tiện lợi, giúp bạn dễ dàng chế biến được nhiều món ăn ngon ngay tại nhà mà không cần phải ra tiệm.',
                'gia_ban'           => 40,
                'gia_khuyen_mai'    => 30,
                'id_chuyen_muc'     => 2,
            ],
            [
                'ten_san_pham'      => 'Nồi chiên không dầu Hafele 11 lít AF-602A (535.43.711)',
                'slug_san_pham'     => Str::slug('Nồi chiên không dầu Hafele 11 lít AF-602A (535.43.711)'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '2',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/10/18/638016824861342736_noi-chien-khong-dau-hafele-11-lit-af-602a-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại nồi: Nồi chiên không dầu',
                'mo_ta_chi_tiet'    => 'Nồi chiên không dầu cỡ lớn 11L AF-602A là sản phẩm nồi chiên không dầu với dung tích lớn đến từ thương hiệu nồi chiên không dầu Hafele, nổi bật với thiết kế cửa kính sang trọng, tích hợp quạt đối lưu và chức năng quay để có thể đồng thời đảm nhiệm cả 2 công năng chiên không dầu và nướng.',
                'gia_ban'           => 20,
                'gia_khuyen_mai'    => 10,
                'id_chuyen_muc'     => 2,
            ],
            [
                'ten_san_pham'      => 'Nồi chiên không dầu Kangaroo 15 lít KG15AF1A',
                'slug_san_pham'     => Str::slug('Nồi chiên không dầu Kangaroo 15 lít KG15AF1A'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '2',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2023/4/12/638168883233262285_noi-chien-khong-dau-kangaroo-15-lit-kg15af1a-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại nồi: Nồi chiên không dầu',
                'mo_ta_chi_tiet'    => 'Nồi chiên không dầu Kangaroo 15 lít KG15AF1A là thiết bị nhà bếp đa năng, có thể thay thế đến 9 loại dụng cụ nhà bếp khác. Với 11 chế độ nấu đa dạng cùng hàng loạt tính năng đáng giá, sản phẩm hứa hẹn sẽ tạo nên những bữa ăn chất lượng, ít béo, đảm bảo sức khỏe cho gia đình, người thân của bạn.',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 19,
                'id_chuyen_muc'     => 2,
            ],
            [
                'ten_san_pham'      => 'Nồi chiên không dầu điện tử Kangaroo 15L KG15AF3A ',
                'slug_san_pham'     => Str::slug('Nồi chiên không dầu điện tử Kangaroo 15L KG15AF3A '),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '2',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/10/14/638013581588506810_noi-chien-khong-dau-dien-tu-kangaroo-15-lit-kg15af3a-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại nồi : Nồi chiên không dầu',
                'mo_ta_chi_tiet'    => 'Nồi chiên không dầu Kangaroo KG15AF3A 15 lít gây ấn tượng với thiết kế hiện đại, dung tích lớn lên đến 15 lít cùng nhiều chế độ nấu đa dạng. Sản phẩm tích hợp mọi công năng hiện đại nhất, mang đến sự tiện lợi cho khách hàng vì tất cả tiện ích đều có sẵn trong một sản phẩm.',
                'gia_ban'           => 89,
                'gia_khuyen_mai'    => 49,
                'id_chuyen_muc'     => 2,
            ],


            //partner 3
            [
                'ten_san_pham'      => 'Bếp đôi hồng ngoại điện từ Kangaroo KG499N',
                'slug_san_pham'     => Str::slug('Bếp đôi hồng ngoại điện từ Kangaroo KG499N'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '2',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/12/29/638079065083711589_bep-doi-hong-ngoai-dien-tu-kangaroo-kg499n-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại bếp: Bếp điện từ',
                'mo_ta_chi_tiet'    => '- Bếp đôi hồng ngoại điện từ Kangaroo KG499N gây chú ý bởi kiểu dáng hiện đại, đơn giản mà đẹp mắt, cùng nhiều chức năng tiện lợi. Bếp KG499N Kangaroo được thiết kế có thể lắp đặt âm tường, vừa vặn trong căn bếp một cách sang trọng, nâng cao tính thẩm mỹ cho mọi không gian nhà bếp.',
                'gia_ban'           => 99,
                'gia_khuyen_mai'    => 83,
                'id_chuyen_muc'     => 3,
            ],
            [
                'ten_san_pham'      => 'Bếp điện từ đôi Kangaroo KG851i ',
                'slug_san_pham'     => Str::slug('Bếp điện từ đôi Kangaroo KG851i '),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '2',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2021/8/19/637649927408010034_bep-dien-tu-doi-kangaroo-kg851i-den-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại bếp: Bếp điện từ',
                'mo_ta_chi_tiet'    => '- Bếp từ đôi Kangaroo KG851i với thiết kế sang trọng, mặt kính Crystallite bền chắc, điều khiển cảm ứng thời thượng và đa dạng các tính năng nấu ăn lẫn bổ trợ, sẽ là chiếc bếp vừa tiện dụng vừa an toàn mà bất cứ gian bếp hiện đại nào cũng cần có.',
                'gia_ban'           => 40,
                'gia_khuyen_mai'    => 29,
                'id_chuyen_muc'     => 3,
            ],
            [
                'ten_san_pham'      => 'Bếp điện từ đôi Kangaroo KG865i',
                'slug_san_pham'     => Str::slug('Bếp điện từ đôi Kangaroo KG865i'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '2',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2021/11/16/637726804260152511_00780836-bep-dien-tu-toshiba-ic-20s3pv-kem-noi-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại bếp: Bếp điện từ',
                'mo_ta_chi_tiet'    => '- Là sản phẩm nhập khẩu được sản xuất tại Thái Lan, Bếp điện từ đôi Kangaroo KG865i gây ấn tượng với thiết kế nguyên khối, chế độ tiết kiệm điện inverter cùng hiệu suất nhiệt ổn định. Sản phẩm có mức giá hợp lý và phù hợp với mọi không gian bếp, cùng công suất mạnh mẽ sẽ giúp bạn nấu nướng nhanh chóng, tiện lợi.',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 3,
            ],
            [
                'ten_san_pham'      => 'Bếp điện từ đơn Toshiba IC-20S3PV (Kèm nồi)',
                'slug_san_pham'     => Str::slug('Bếp điện từ đơn Toshiba IC-20S3PV (Kèm nồi)'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '2',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/10/24/638022176226920789_bep-dien-tu-doi-kangaroo-kg865i-DD.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại bếp: Bếp điện từ',
                'mo_ta_chi_tiet'    => 'Với thiết kế mỏng sang trọng nhưng vẫn không kém phần chắc chắn, cùng với đó là hiệu năng mạnh mẽ và các tính năng đảm bảo an toàn, Bếp điện từ Toshiba IC-20S3PV là sản phẩm bếp điện từ đa năng có thể đáp ứng được nhu cầu nấu nướng của bất kì người nội trợ nào.',
                'gia_ban'           => 15,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 3,
            ],
            [
                'ten_san_pham'      => 'Bếp điện từ đơn Toshiba IC-20S2PV (Kèm nồi)',
                'slug_san_pham'     => Str::slug('Bếp điện từ đơn Toshiba IC-20S2PV (Kèm nồi)'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '3',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2021/11/16/637726795263255013_00780835-bep-dien-tu-toshiba-ic-20s2pv-kem-noi-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại bếp: Bếp điện từ',
                'mo_ta_chi_tiet'    => 'Bếp điện từ Toshiba IC-20S2PV được trang bị mắt bếp làm từ chất liệu kính Ceramic Hegon đen cao cấp của Đức có độ sáng bóng vượt trội. Đồng thời, chất liệu ceramic tinh thể đen này cũng có khả năng chịu được nhiệt độ cao từ 600 đến 1150 độ C, chịu lực đến 150kg, chống trầy xước đến tối đa, độ bền bỉ cao theo thời gian và rất khó nứt vỡ. Chất liệu này cũng khó bị bám bẩn do đó cũng rất dễ vệ sinh, bạn chỉ cần dùng khăn ẩm kết hợp với các chất tẩy rửa thông thường cho nhà bếp là sẽ có thể dễ dàng loại bỏ được các vết bẩn thức ăn, nhanh chóng trả lại cho bếp vẻ ngoài bóng loáng như ban đầu.',
                'gia_ban'           => 39,
                'gia_khuyen_mai'    => 29,
                'id_chuyen_muc'     => 3,
            ],
            [
                'ten_san_pham'      => 'Bếp điện từ đôi Kangaroo KG498N ',
                'slug_san_pham'     => Str::slug('Bếp điện từ đôi Kangaroo KG498N '),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '3',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/10/24/638022273175781511_bep-dien-tu-doi-kangaroo-kg498n-dd.jpgg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Bếp điện từ: Bếp điện từ',
                'mo_ta_chi_tiet'    => 'Bếp điện từ đôi Kangaroo KG498N sở hữu thiết kế sang trọng, đa chức năng nấu nướng, dễ dàng sử dụng và bảo đảm an toàn tuyệt đối, hiện đang là xu thế sử dụng của nhiều căn bếp hiện đại, thông minh.',
                'gia_ban'           => 29,
                'gia_khuyen_mai'    => 24,
                'id_chuyen_muc'     => 3,
            ],
            [
                'ten_san_pham'      => 'Bếp điện từ Sunhouse SHD6802',
                'slug_san_pham'     => Str::slug('Bếp điện từ Sunhouse SHD6802'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '3',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2021/12/29/637763872113062762_bep-dien-tu-sunhouse-shd6802-den-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại bếp: Bếp điện từ',
                'mo_ta_chi_tiet'    => 'Mặt bếp của bếp từ Sunhouse SHD6802 được phủ một lớp kính cường lực có khả năng chịu được nhiệt độ lên đến 600 độ C, ngoài ra cũng cho bếp khả năng chịu lực cực tốt để bạn có thể yên tâm đặt nồi chứa đầy thức ăn lên bếp mà không sợ làm hư hỏng hay ảnh hưởng đến các linh kiện bên dưới mặt bếp. Ngoài ra, mặt kính này còn được phủ một lớp ceramic để chống trầy xước, đồng thời giúp cho mặt bếp ít dính bẩn hơn, người dùng cũng dễ dàng làm sạch bếp hơn chỉ với khăn ẩm và các chất tẩy rửa nhà bếp thông thường.',
                'gia_ban'           => 70,
                'gia_khuyen_mai'    => 65,
                'id_chuyen_muc'     => 3,
            ],
            [
                'ten_san_pham'      => 'Bếp điện từ đôi Sunhouse SHB9101 ',
                'slug_san_pham'     => Str::slug('Bếp điện từ đôi Sunhouse SHB9101 '),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '3',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2021/12/3/637741365636299516_bep-dien-tu-doi-sunhouse-shb9101-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại bếp: Bếp điện từ',
                'mo_ta_chi_tiet'    => 'VBếp từ đôi Sunhouse SHB9101 có thiết kế phẳng hiện đại, sử dụng mặt kính cao cấp bóng loáng với 2 mặt bếp công suất cao, đem đến cho bạn không gian nấu nướng thoải mái, tiện dụng và an toàn nhất.',
                'gia_ban'           => 70,
                'gia_khuyen_mai'    => 65,
                'id_chuyen_muc'     => 3,
            ],
            // partner 4
            [
                'ten_san_pham'      => 'Bộ nồi inox 5 đáy Sunhouse SH888',
                'slug_san_pham'     => Str::slug('Bộ nồi inox 5 đáy Sunhouse SH888'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '4',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2023/1/10/638089377246664416_bo-noi-inox-5-day-sunhouse-sh888-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Nồi ',
                'mo_ta_chi_tiet'    => 'Bộ nồi inox 5 đáy Sunhouse SH888 không chỉ có diện mạo bắt mắt mà còn sở hữu hàng loạt ưu điểm tuyệt vời. Với 3 kích thước nồi phổ biến, sản phẩm có thể đáp ứng cho nhiều nhu cầu nấu nướng khác nhau từ luộc trứng, kho thịt, nấu canh hoặc lẩu nhưng vẫn đảm bảo an toàn cho sức khỏe người sử dụng.',
                'gia_ban'           => 29,
                'gia_khuyen_mai'    => 27,
                'id_chuyen_muc'     => 4,
            ],
            [
                'ten_san_pham'      => 'Bộ 3 nồi inox 5 đáy - đáy từ Sunhouse SH781',
                'slug_san_pham'     => Str::slug('Bộ 3 nồi inox 5 đáy - đáy từ Sunhouse SH781'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '4',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2021/8/5/637637752859403123_bo-3-noi-inox-5-day-day-tu-sunhouse-sh781-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Nồi',
                'mo_ta_chi_tiet'    => 'Bộ sản phẩm Bộ 3 nồi inox 5 đáy Sunhouse SH781 với các kích thước khác nhau, nổi trội với bộ đế dày 5 lớp cho phép nó có thể được sử dụng trên cả bếp ga lẫn bếp từ, đảm bảo đáp ứng được đa dạng nhu cầu nấu ăn cho mọi gia đình.  ',
                'gia_ban'           => 39,
                'gia_khuyen_mai'    => 26,
                'id_chuyen_muc'     => 4,
            ],
            [
                'ten_san_pham'      => 'Bộ 3 nồi inox 5 đáy - đáy từ Sunhouse SHG788',
                'slug_san_pham'     => Str::slug('Bộ 3 nồi inox 5 đáy - đáy từ Sunhouse SHG788'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '4',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2021/8/5/637637740978859187_bo-3-noi-inox-5-day-day-tu-sunhouse-shg788-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Nồi',
                'mo_ta_chi_tiet'    => 'Bộ 3 nồi inox 5 đáy Sunhouse SHG788 là sản phẩm đến từ thương hiệu hàng gia dụng uy tín Sunhouse, được làm từ chất liệu inox cao cấp nguyên khối bền bỉ, thiết kế quai núm và tai cầm đẹp mắt, đem đến điểm nhấn bắt mắt cho gian bếp của bạn.',
                'gia_ban'           => 34,
                'gia_khuyen_mai'    => 23,
                'id_chuyen_muc'     => 4,
            ],
            [
                'ten_san_pham'      => 'Bộ nồi inox 3 chiếc 3 đáy nắp kính Sunhouse SHG2303MSA',
                'slug_san_pham'     => Str::slug('Bộ nồi inox 3 chiếc 3 đáy nắp kính Sunhouse SHG2303MSA'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '4',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2023/4/20/638175984710585377_bo-noi-inox-3-chiec-3-day-nap-kinh-sunhouse-shg2303msa-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Nồi',
                'mo_ta_chi_tiet'    => 'Với 3 kích cỡ khác nhau, bộ nồi inox 3 chiếc 3 đáy nắp kính Sunhouse SHG2303MSA có thể đáp ứng nhiều nhu cầu nấu nướng đa dạng. Nhờ khả năng truyền nhiệt và tỏa nhiệt tốt, thức ăn trong nồi sẽ được nấu chín đều và nhanh chóng, giúp bạn tiết kiệm thời gian nấu nướng hiệu quả.',
                'gia_ban'           => 39,
                'gia_khuyen_mai'    => 29,
                'id_chuyen_muc'     => 4,
            ],
            //partner 5

            [
                'ten_san_pham'      => 'Chảo chống dính đáy từ Elmich Smartcook SM5744MN 24cm',
                'slug_san_pham'     => Str::slug('Chảo chống dính đáy từ Elmich Smartcook SM5744MN 24cm'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '5',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/7/11/637931529896434399_chao-inox-3-day-chong-dinh-day-tu-goldsun-gpa1400-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Chảo chống dính',
                'mo_ta_chi_tiet'    => 'Không chỉ có kiểu dáng đẹp, Chảo chống dính đáy từ Elmich Smartcook SM5744MN 24cm còn sở hữu chất liệu nhôm bền bỉ mà giá thành lại phải chăng. Sản phẩm có diện tích rộng nên phù hợp với nhiều nhu cầu sử dụng.',
                'gia_ban'           => 29,
                'gia_khuyen_mai'    => 24,
                'id_chuyen_muc'     => 5,
            ],
            [
                'ten_san_pham'      => 'Chảo inox 3 đáy chống dính đáy từ Goldsun GPA1400-18IH 18cm',
                'slug_san_pham'     => Str::slug('Chảo inox 3 đáy chống dính đáy từ Goldsun GPA1400-18IH 18cm'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '5',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2023/1/10/638089385973884510_chao-nhom-chong-dinh-goldsun-gpa1210-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Chảo chống dính',
                'mo_ta_chi_tiet'    => 'Đến từ thương hiệu thuộc top được ưa chuộng nhất Việt Nam hiện nay, chảo inox 3 đáy chống dính đáy từ Goldsun GPA1400-18IH 18cm có thiết kế đơn giản mà hài hòa, được chế tác từ vật liệu cao cấp. Sản phẩm này chắc chắn sẽ hỗ trợ bạn nấu các món ăn hàng ngày được dễ dàng, thoải mái hơn.',
                'gia_ban'           => 70,
                'gia_khuyen_mai'    => 60,
                'id_chuyen_muc'     => 5,
            ],
            [
                'ten_san_pham'      => 'Chảo nhôm chống dính GOLDSUN GPA1210-24',
                'slug_san_pham'     => Str::slug('Chảo nhôm chống dính GOLDSUN GPA1210-24'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '5',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/7/11/637931345560136757_Chao-chao-nhom-sau-long-chong-dinh-day-tu-20cm-goldsun-gpa1004-20ih-den-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Chảo chống dính',
                'mo_ta_chi_tiet'    => '- Chảo nhôm chống dính Goldsun GPA1210-24 được thiết kế đơn giản nhưng vẫn bắt mắt, hài hòa với mọi không gian bếp, ngoài ra còn nổi bật với tay cầm bọc nhựa cách nhiệt và thiết kế chống trơn trượt, luôn đảm bảo an toàn mỗi khi sử dụng. ',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 5,
            ],
            [
                'ten_san_pham'      => 'Chảo nhôm sâu lòng chống dính đáy từ 20cm Goldsun GPA1004-20IH',
                'slug_san_pham'     => Str::slug('Chảo nhôm sâu lòng chống dính đáy từ 20cm Goldsun GPA1004-20IH'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '5',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2023/10/25/638338275287543638_chao-chong-dinh-day-tu-elmich-smartcook-sm5744mn-24cm-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Chảo chống dính',
                'mo_ta_chi_tiet'    => '- Không chỉ có giá thành phải chăng, Chảo nhôm sâu lòng chống dính đáy từ 20cm Goldsun GPA1004-20IH gần như sở hữu tất cả mọi chức năng cần có để hỗ trợ việc nấu nướng của bạn tiện lợi hơn. Với chất liệu bền bỉ, kiểu dáng hiện đại, sử dụng được cho nhiều loại bếp, đây thực sự là lựa chọn hoàn hảo cho những khách hàng có nhu cầu tìm kiếm chiếc chảo chân ái.',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 5,
            ],

            // partner 6
            [
                'ten_san_pham'      => 'Máy lọc không khí LG PuriCare 360 Hit AS60GHWG0 41W',
                'slug_san_pham'     => Str::slug('Máy lọc không khí LG PuriCare 360 Hit AS60GHWG0 41W'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '6',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2023/3/2/638133681476034794_may-loc-khong-khi-lg-puricare-as60ghwg0-41w-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Máy lọc không khí',
                'mo_ta_chi_tiet'    => '- Mật độ dân cư đông đúc tại thành phố khiến các tác nhân gây hại trong không khí hoành hoành. Do đó, sự hiện diện của một chiếc máy lọc không khí có thể lọc bỏ vi khuẩn, virus, bụi mịn, bụi siêu mịn và chất gây dị ứng như LG PuriCare 360 Hit AS60GHWG0 41W là cực kỳ cần thiết. Sản phẩm sẽ liên tục đo đạc chất lượng không khí và tự hoạt động để trả lại không gian sống trong lành, an toàn và sạch sẽ. Giúp phòng tránh các bệnh lý về hô hấp hiệu quả..',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 6,
            ],
            [
                'ten_san_pham'      => 'Máy lọc không khí xông tinh dầu Levoit LV-H128',
                'slug_san_pham'     => Str::slug('Máy lọc không khí xông tinh dầu Levoit LV-H128'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '6',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2023/7/31/638264106766970827_may-loc-khong-khi-xong-tinh-dau-levoit-lv-h128-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Máy lọc không khí',
                'mo_ta_chi_tiet'    => '- Máy lọc không khí xông tinh dầu Levoit LV-H128 là một giải pháp hoàn hảo cho không gian sống của bạn. Nhờ khả năng lọc không khí hiệu quả và tính năng xông tinh dầu thư giãn, sản phẩm này mang đến không gian trong lành và thư thái cho cả gia đình. ',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 6,
            ],
            [
                'ten_san_pham'      => 'Máy lọc không khí Levoit Core 300',
                'slug_san_pham'     => Str::slug('Máy lọc không khí Levoit Core 300'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '6',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2023/7/31/638264133355108433_may-loc-khong-khi-levoit-core-300-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Máy lọc không khí',
                'mo_ta_chi_tiet'    => '- Máy lọc không khí Levoit Core 300 sở hữu thiết kế hình trụ tròn màu trắng đơn giản, mang đến vẻ ngoài hiện đại, tinh tế cho không gian sống. Sản phẩm có kiểu dáng nhỏ gọn với trọng lượng chỉ 3,4 kg và kích thước 22 x 22 x 36 cm nên rất dễ dàng trong việc nâng máy và di chuyển từ nơi này sang nơi khác, phù hợp để đặt tại mọi ngóc ngách trong phòng.',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 6,
            ],
            [
                'ten_san_pham'      => 'Máy lọc không khí chống dị ứng thú cưng Levoit Vital 100S',
                'slug_san_pham'     => Str::slug('Máy lọc không khí chống dị ứng thú cưng Levoit Vital 100S'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '6',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2023/7/31/638264149785798760_may-loc-khong-khi-chong-di-ung-thu-cung-levoit-vital-100s-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Máy lọc không khí',
                'mo_ta_chi_tiet'    => '- Từ nay, việc nuôi thú cưng sẽ trở nên thoải mái, dễ thở hơn khi sở hữu máy lọc không khí chống dị ứng thú cưng Levoit Vital 100S. Với hệ thống lọc 3 lớp tiên tiến, sản phẩm đảm bảo khả năng loại bỏ các hạt bụi, phấn hoa, vi khuẩn và mùi khó chịu, mang đến không gian trong lành, thoáng đãng cho cả gia đình.',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 6,
            ],
            //partner 7
            [
                'ten_san_pham'      => 'Máy sấy tóc Sunhouse SHD2306 ',
                'slug_san_pham'     => Str::slug('Máy sấy tóc Sunhouse SHD2306 '),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '7',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2023/2/15/638120687931590084_may-say-toc-sunhouse-shd2306-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Máy lọc không khí',
                'mo_ta_chi_tiet'    => '- Sở hữu thiết kế tối giản, gọn gàng và diện mạo màu đen sang trọng, máy sấy tóc Sunhouse SHD2306 dễ dàng tạo hòa hợp với mọi không gian. Sản phẩm đến từ thương hiệu nổi tiếng với chế độ bảo hành tốt, giúp khách hàng yên tâm khi sử dụng.',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 7,
            ],
            [
                'ten_san_pham'      => 'Máy sấy tóc Sunhouse SHD2308W',
                'slug_san_pham'     => Str::slug('Máy sấy tóc Sunhouse SHD2308W'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '7',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2021/6/28/637604746136822952_may-say-toc-sunhouse-shd2308w-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Máy lọc không khí',
                'mo_ta_chi_tiet'    => '- Vào những dịp cần đi ra ngoài hoặc thời tiết mưa nhiều, trời lạnh thì máy sấy tóc Sunhouse SHD2308W là giải pháp hữu ích giúp tóc được sấy khô nhanh chóng, dễ dàng tạo kiểu cũng như ngăn ngừa nguy cơ gây ra các bệnh về da đầu. Không chỉ có thiết kế đẹp mà sản phẩm còn có nhiều chế độ sấy khác nhau, đáp ứng mọi nhu cầu sử dụng. ',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 7,
            ],
            [
                'ten_san_pham'      => 'Máy sấy tóc Sunhouse SHD2305',
                'slug_san_pham'     => Str::slug('Máy sấy tóc Sunhouse SHD2305'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '7',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2021/6/26/637603273860540080_may-say-toc-sunhouse-shd2305-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Máy lọc không khí',
                'mo_ta_chi_tiet'    => '- Vào những dịp cần đi ra ngoài hoặc thời tiết mưa nhiều, trời lạnh thì máy sấy tóc Sunhouse SHD2308W là giải pháp hữu ích giúp tóc được sấy khô nhanh chóng, dễ dàng tạo kiểu cũng như ngăn ngừa nguy cơ gây ra các bệnh về da đầu. Không chỉ có thiết kế đẹp mà sản phẩm còn có nhiều chế độ sấy khác nhau, đáp ứng mọi nhu cầu sử dụng.',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 7,
            ],
            [
                'ten_san_pham'      => 'Máy sấy tóc Philips HP8108',
                'slug_san_pham'     => Str::slug('Máy sấy tóc Philips HP8108'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '7',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2021/5/31/637580659495052368_may-say-toc-philips-hp8108-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Máy lọc không khí',
                'mo_ta_chi_tiet'    => '- Không chỉ tập trung vào mục tiêu làm khô tóc, máy sấy tóc Philips HP8108 còn là trợ thủ đắc lực giúp bạn tạo mẫu tóc theo đúng ý muốn của bạn. Sản phẩm được thiết kế rất gọn gàng, tiện lợi để sử dụng ở bất cứ đâu, dù là tại nhà hay trong những chuyến du lịch/công tác xa nhà. Với Philips HP8108, bạn luôn sở hữu mái tóc ưng ý mọi nơi mọi lúc.',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 7,
            ],
            //partner 8
            [
                'ten_san_pham'      => 'Đèn bàn Sunhouse Apex APE-01LED  ',
                'slug_san_pham'     => Str::slug('Đèn bàn Sunhouse Apex APE-01LED  '),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '8',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/3/28/637840739239347670_den-ban-apex-ape-01led-trang-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Đèn bàn',
                'mo_ta_chi_tiet'    => '- Đèn bàn Sunhouse Apex APE-01LED gây ấn tượng nhờ khả năng chiếu sáng tốt và ánh sáng ổn định, không nhấp nháy trong suốt quá trình hoạt động. Bạn có thể điểu chỉnh chế độ ánh sáng của Đèn bàn APE-01LED Apex để phù hợp với nhu cầu sử dụng, từ học tập, làm việc, đèn ngủ hay làm sáng bàn phím máy tính đều rất đơn giản, tiện lợi.',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 8,
            ],
            [
                'ten_san_pham'      => 'Đèn bàn Sunhouse SHE-17LED-A6',
                'slug_san_pham'     => Str::slug('Đèn bàn Sunhouse SHE-17LED-A6'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '8',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/3/28/637840768533142147_den-ban-sunhouse-she-17led-a6-vang-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Đèn bàn',
                'mo_ta_chi_tiet'    => '- Đèn bàn Sunhouse SHE-17LED-A6 gây ấn tượng nhờ thiết kế hoạt hình đáng yêu, kết hợp cùng màu sắc bắt mắt hết sức thân thiện với các bạn nhỏ. Không những thế, sản phẩm còn được làm từ những chất liệu tốt nhất để đảm bảo thời gian hoạt động bền bỉ, tiết kiệm kinh tế cho người sử dụng.',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 8,
            ],
            [
                'ten_san_pham'      => 'Đèn bàn sạc Led Comet CT175',
                'slug_san_pham'     => Str::slug('Đèn bàn sạc Led Comet CT175'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '8',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/10/4/638004884529038526_den-ban-sac-led-comet-ct175-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Đèn bàn',
                'mo_ta_chi_tiet'    => '- Đèn bàn sạc Led Comet CT175 có thiết kế đơn giản mà vẫn bắt mắt, cung cấp cho người dùng bóng đèn với 3 màu sắc khác nhau và có thể điều chỉnh được cường độ sáng, đáp ứng đa dạng nhu cầu làm việc và học tập trong mọi không gian.',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 8,
            ],
            [
                'ten_san_pham'      => 'Đèn bàn Comet CT413 ',
                'slug_san_pham'     => Str::slug('Đèn bàn Comet CT413 '),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '8',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/6/14/637907998997353978_den-ban-comet-vang-ct413y-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Đèn bàn',
                'mo_ta_chi_tiet'    => '- Gây ấn tượng nhờ thiết kế và màu sắc bắt mắt ngay từ ánh nhìn đầu tiên, Đèn bàn Comet Vàng CT413Y cung cấp cho người dùng ánh sáng trắng ổn định không gây mỏi mắt, chống cận thị, do đó rất phù hợp để trang bị trên bàn học hay bàn làm việc tại nhà.',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 8,
            ],
            //partner 9
            [
                'ten_san_pham'      => 'Máy rửa bát mini 6 bộ Hafele HDW-T50B (539.20.600)',
                'slug_san_pham'     => Str::slug('Máy rửa bát mini 6 bộ Hafele HDW-T50B (539.20.600)'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '9',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/10/24/638022063305678194_may-rua-bat-doc-lap-15-bo-hafele-hdw-f60e-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Máy rửa bát',
                'mo_ta_chi_tiet'    => '- Sở hữu kiểu dáng sang trọng cùng hàng loạt năng hữu ích, Máy rửa bát độc lập Hafele HDW-T50B (539.20.600) gây ấn tượng với người dùng ngay từ cái nhìn đầu tiên. Là sản phẩm cao cấp đến từ thương hiệu uy tín, Máy rửa bát độc lập HDW-T50B Hafele rất tiết kiệm không gian, chắc chắn sẽ giúp bạn giải quyết nhu cầu rửa bát dĩa một cách nhanh chóng, thuận tiện nhất!.',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 9,
            ],
            [
                'ten_san_pham'      => 'Máy rửa bát mini 6 bộ Hafele HDW-T50A (538.21.190)',
                'slug_san_pham'     => Str::slug('Máy rửa bát mini 6 bộ Hafele HDW-T50A (538.21.190)'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '9',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/10/24/638022072213573220_may-rua-bat-doc-lap-12-bo-hafele-hdw-f60g-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Máy rửa bát',
                'mo_ta_chi_tiet'    => '- Dù có kiểu dáng nhỏ gọn, máy rửa bát để bàn Hafele HDW-T50A (538.21.190) vẫn sở hữu hàng loạt năng hữu ích, hoàn toàn đáp ứng được cho những người dùng có nhu cầu tìm kiếm một chiếc máy rửa bát thông minh, tiên tiến, tiết kiệm không gian nhưng vẫn có thể giải quyết nhu cầu rửa bát một cách nhanh chóng, thuận tiện.',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 9,
            ],
            [
                'ten_san_pham'      => 'Máy rửa bát độc lập 12 bộ Hafele HDW-F60G (535.29.590)',
                'slug_san_pham'     => Str::slug('Máy rửa bát độc lập 12 bộ Hafele HDW-F60G (535.29.590)'),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '9',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/10/20/638018618562047411_may-rua-bat-mini-6-bo-hafele-hdw-t50a-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Máy rửa bát',
                'mo_ta_chi_tiet'    => '- Máy rửa bát độc lập 12 bộ Hafele HDW-F60G là sản phẩm đến từ thương hiệu Đức Hafele, có dung tích lớn và nhiều chương trình rửa khác nhau, đặc biệt còn có chế độ Rửa nửa tải giúp người nội trợ giải phóng sức lao động một cách hiệu quả mà vẫn tiết kiệm nhất.',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 9,
            ],
            [
                'ten_san_pham'      => 'Máy rửa bát độc lập 15 bộ Hafele HDW-F60E (538.21.200) ',
                'slug_san_pham'     => Str::slug('Máy rửa bát độc lập 15 bộ Hafele HDW-F60E (538.21.200) '),
                'so_luong_nhap'     => random_int(100, 300),
                'so_luong_ban'      => random_int(10, 100),
                'id_partner'        => '9',
                'hinh_anh'          => 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/3/31/637843407932184902_may-rua-bat-doc-lap-hafele-hdw-t50b-bac-dd.jpg',
                'tinh_trang'        => '1',
                'mo_ta_ngan'        => 'Loại: Máy rửa bát',
                'mo_ta_chi_tiet'    => '- Máy rửa bát độc lập 14 bộ Hafele HDW-F60E sở hữu thiết kế gọn gàng, 8 chế độ rửa ưu việt cùng nhiều tính năng bổ trợ tiện dụng, giúp người nội trợ giải phóng sức lao động một cách hiệu quả nhất trong gian bếp.',
                'gia_ban'           => 19,
                'gia_khuyen_mai'    => 12,
                'id_chuyen_muc'     => 9,
            ],
        ]);
    }
}
